Traceback (most recent call last):
  File "/home/users/vcbenedet/FM30k/metricas.py", line 402, in <module>
    metricas(images_names, all_legendas, image_to_legend_indices, save_path_embeddings, modelo_openai_input_path_name)
  File "/home/users/vcbenedet/FM30k/metricas.py", line 356, in metricas
    metricas_img = evaluate_fold_image_to_text(val_indices, image_embeddings, text_embeddings, all_legendas, image_to_legend_indices, val_legend_indices)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/vcbenedet/FM30k/metricas.py", line 187, in evaluate_fold_image_to_text
    similarity = batch @ text_embeddings_val.T
                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: expected m1 and m2 to have the same dtype, but got: c10::Half != float
